
%analysis01.m
%
%
%
%author : steeve laquitaine
%  date : 160916
%purpose: model data sample of actual brain voxel responses with a 5 fold 
%         cross-validated forward model that assumes voxel responses are 
%         the linear sum of 5 sinewave "channel" function with 5 different 
%         direction preference (phase) raised to power 4.
%         Data are concatenated over scans from diffferent prior
%         conditions (prior mean are 135 and 225 deg)
%
%
%
%% load actual brain responses
%Ni instance x Nv voxels matrices of responses to stimulus directions 
%were collected in two conditions: In one condition, the trial distribution
%of the directions was a von Mises with a mean of 225 deg and std 80 deg;
%in the other condition the prior mean was 135 deg.
%The two matrices were originally generated by two functions which takes
%.nifti fMRI files containing subject brain responses, .mat files 
%containing task parameters and subjects behavioral responses, and .mat 
%files defining the subject's visual areas as input :
%
%             >> slfmriInitAnalysisTaskDotDirfMRI05 
%             >> d = slfmriGetDBoverSessions(o,varargin); 
%
%Each matrix stacks data from 3 sessions from the same subject.
%We collect both matrices and stack them together
%prior 135
load('data/prior135/V1toMT/instanceMatrix.mat')
instances135 = d.instances;
svec135 = d.myRandomDir;
%prior 225
load('data/prior225/V1toMT/instanceMatrix.mat')
instances225 = d.instances;
svec225 = d.myRandomDir;
%stack priors
instances = [instances135;instances225];
svec = [svec135; svec225]; 
%%get most motion-responsive voxels
%%note that it seems to hurt the representation to 
%%remove voxels
% load('data_sample/r2_V1.mat')
% instances = instances(:,r2 >= 0.05);

%% cross-validated forward modeling of the dataset
%match channel preferences to displayed directions
fm.phi_k = unique(svec);
fm.power = 9;
fm = slvoxfmKFoldCVdec(instances,svec,5,fm);